apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx-blue
  replicas: 0
  template:
    metadata:
      labels:
        app: nginx-blue
    spec:
      containers:
      - name: nginx-blue
        image: nginx:1.21.1
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
