apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rollout-hpa-migration
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: rollout-migration
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 7
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 7