
apiVersion: v1
kind: Service
metadata:
  name: rollout-svc-migration-active
  namespace: test
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: nginx-blue
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-svc-migration-preview
  namespace: test
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: nginx-blue
