apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-migration
  namespace: test
  annotations: {}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    blueGreen:
      activeMetadata:
        labels:
          role: active
      previewMetadata:
        labels:
          role: preview
      activeService: rollout-svc-migration-active
      previewService: rollout-svc-migration-preview
      autoPromotionEnabled: true
      scaleDownDelaySeconds: 120
      abortScaleDownDelaySeconds: 30
      scaleDownDelayRevisionLimit: 4
      antiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            weight: 1 
  selector:
    matchLabels:
      app: nginx-blue
  workloadRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-blue
  progressDeadlineSeconds: 900
  progressDeadlineAbort: true
  rollbackWindow:
    revisions: 5