apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rollout-hpa-migration
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-blue
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 30
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30